nsd_user: "{{ __nsd_user }}"
nsd_group: "{{ __nsd_group }}"
nsd_db_dir: "{{ __nsd_db_dir }}"
nsd_run_dir: "{{ __nsd_run_dir }}"
nsd_conf_dir: "{{ __nsd_conf_dir }}"
nsd_conf: "{{ nsd_conf_dir }}/nsd.conf"
nsd_zonesdir: "{{ nsd_conf_dir }}"
nsd_flags: ""

nsd_server_count: 1
nsd_ip_addresses: ["0.0.0.0", "::0"]
nsd_reuseport: "no"
nsd_do_ip4: "yes"
nsd_do_ip6: "no"
nsd_port: 53
nsd_verbosity: 0
nsd_chroot_enable: false
nsd_chroot_dir: "{{ nsd_conf_dir }}"
nsd_hide_version: "no"
nsd_minimal_responses: "no"
nsd_statistics: 0 # or 3600
nsd_round_robin: "no"

nsd_remote_control: "no"
nsd_control_interface: [ "127.0.0.1" ]
nsd_control_port: 8952

nsd_server_key_file:   "{{ nsd_conf_dir }}/nsd_server.key"
nsd_server_cert_file:  "{{ nsd_conf_dir }}/nsd_server.pem"
nsd_control_key_file:  "{{ nsd_conf_dir }}/nsd_control.key"
nsd_control_cert_file: "{{ nsd_conf_dir }}/nsd_control.pem"

nsd_custom_server_config:
