# Start with the ubuntu image
FROM centos:7
# Install ansible dependencies
RUN yum install -y python-yaml python-jinja2 git
# Clone ansible repo (could also add the ansible PPA and do an apt-get install instead)
RUN git clone http://github.com/ansible/ansible.git /tmp/ansible

# Set variables for ansible
WORKDIR /tmp/ansible
ENV PATH "/tmp/ansible/bin:/sbin:/usr/sbin:/usr/bin:${PATH}"
ENV ANSIBLE_LIBRARY /tmp/ansible/library
ENV PYTHONPATH /tmp/ansible/lib:$PYTHON_PATH

# Install requirements
ADD ./requirements.yml /etc/ansible/requirements.yml
WORKDIR /etc/ansible
RUN ansible-galaxy install -r requirements.yml

# Run ansible using the playbook
ADD ./ /etc/ansible/
RUN ansible-playbook test.yml -i hosts -c local --diff
