sudo: required
group: edge
language: python
services:
  - docker
before_install:
  - docker info
  - docker version
install:
  - pip install molecule
  - pip install docker
  # - pip install required driver (e.g. docker, python-vagrant, shade)
script:
  - molecule test
