---
language: python
python: "2.7"
cache:
  directories:
    - required-roles
    - $HOME/.cache/pip

env:
  - ANSIBLE_ROLES_PATH=roles:required-roles

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible ansible-lint yamllint

  # Get dependencies from galaxy
  - ansible-galaxy install -r requirements.yml -p required-roles

script:
  # Check the role/playbook's syntax. Linting
  - ./lint
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i 127.0.0.1, test.yml --connection=local --become -v
  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i 127.0.0.1, test.yml --connection=local --become
  # | grep -q 'changed=0.*failed=0'
  # && (echo 'Idempotence test: pass' && exit 0)
  # || (echo 'Idempotence test: fail' && exit 1)
  # Make a DNS request to check it's working properly
  - dig @127.0.0.1 -p553
