#!/bin/bash

if ! command -v travis >/dev/null 2>&1 && command -v gem >/dev/null 2>&1 && [ "$TRAVIS" != "true" ]; then
    yes | gem install travis --no-rdoc --no-ri
fi

if ! command -v ansible-playbook >/dev/null 2>&1; then
    pip install ansible
fi

if ! command -v yamllint >/dev/null 2>&1; then
    pip install yamllint
fi

if ! command -v ansible-lint >/dev/null 2>&1; then
    pip install ansible-lint
fi

if [ "$TRAVIS" != "true" ]; then
    travis lint .travis.yml
fi
ansible-playbook playbook.yml -i hosts --syntax-check
ansible-playbook test.yml -i hosts --syntax-check
# shellcheck disable=SC2046
yamllint $(find . -name '*.yml') # we want word splitting
ansible-lint --exclude=required-roles --exclude="$HOME/.ansible/roles" playbook.yml
