---

- src: https://github.com/jeffwidman/ansible-yum-cron
  scm: git
  version: master
  name: jeffwidman.yum-cron

- src: https://github.com/PowerDNS/pdns_recursor-ansible
  scm: git
  version: master
  name: PowerDNS.pdns_recursor

# rec_control dump-cache

- src: https://github.com/PowerDNS/dnsdist-ansible
  scm: git
  version: master
  name: PowerDNS.dnsdist

- src: publicarray.unbound

- src: jnv.unattended-upgrades
  version: master
  name: jnv.unattended-upgrades

- src: https://github.com/jffz/ansible-netdata
  scm: git
  version: master
  name: jffz.netdata


- src: geerlingguy.repo-epel
  version: master
  name: geerlingguy.repo-epel
