---

- src: https://github.com/jeffwidman/ansible-yum-cron
  scm: git
  version: master
  name: jeffwidman.yum-cron

- src: https://github.com/publicarray/ansible-role-unbound
  scm: git
  version: master
  name: publicarray.unbound

- src: https://github.com/jnv/ansible-role-unattended-upgrades
  scm: git
  version: master
  name: jnv.unattended-upgrades

- src: https://github.com/jffz/ansible-netdata
  scm: git
  version: master
  name: jffz.netdata

- src: https://github.com/geerlingguy/ansible-role-repo-epel
  scm: git
  version: master
  name: geerlingguy.repo-epel
