---
- name: Install unbound, pdns_recursor, dnsdist, and dnscrypt-wrapper
  hosts: dns-server
  remote_user: root

  roles:
    - common
    - { role: jnv.unattended-upgrades, when: ansible_os_family == 'Darwin' }
    - { role: jeffwidman.yum-cron, when: ansible_os_family == 'RedHat' }
    - { role: unbound, when: unbound == true, tags: [unbound] }
    - { role: PowerDNS.pdns_recursor, when: pdns_recursor == true, tags: [pdns_recursor] }
    - { role: PowerDNS.dnsdist, when: dnsdist == true, tags: [dnsdist] }
    - { role: dnsdist-post, when: dnsdist == true, tags: [dnsdist]}
    - { role: dnscrypt-wrapper, when: dnscrypt_wrapper == true, tags: [dnscrypt_wrapper] }
    - { role: jffz.netdata, when: netdata == true, tags: [netdata] }
