---
- name: Install DNS Resolver
  hosts: all
  become: true
  # strategy: debug
  remote_user: root
  roles:
    - { role: geerlingguy.repo-epel, when: ansible_os_family == 'RedHat', tags: [init] }
    - { role: common, tags: [init] }
    - { role: jnv.unattended-upgrades, when: ansible_os_family == 'Debian', tags: [init] }
    - { role: jeffwidman.yum-cron, when: ansible_os_family == 'RedHat', tags: [init] }
    - { role: nsd, when: opennic == true, tags: [nsd, opennic] }
    - { role: publicarray.unbound, tags: [unbound] }
    - { role: PowerDNS.dnsdist, when: dnsdist == true and ansible_os_family != 'FreeBSD' and ansible_os_family != 'OpenBSD', tags: [dnsdist] }
    - { role: dnsdist-post, when: dnsdist == true, tags: [dnsdist]}
    - { role: dnscrypt-wrapper, when: dnscrypt_wrapper == true, tags: [dnscrypt_wrapper] }
    # - { role: netdata, when: netdata == true, tags: [netdata] }
  vars:
    - unbound_tls_cert_provider: selfsigned
  environment:
    PATH: /usr/local/bin:/usr/local/sbin:{{ansible_env.PATH}}
