---
- name: Install unbound, pdns_recursor, dnsdist, and dnscrypt-wrapper
  hosts: localhost
  remote_user: root

  roles:
    - common
    - { role: jnv.unattended-upgrades, when: ansible_os_family == 'Darwin' }
    - { role: jeffwidman.yum-cron, when: ansible_os_family == 'RedHat' }
    - { role: nsd, when: opennic == true, tags: [nsd, opennic] }
    - { role: unbound, when: dns_recursor == 'unbound', tags: [unbound] }
    - { role: PowerDNS.pdns_recursor, when: dns_recursor == 'pdns_recursor', tags: [pdns_recursor] }
    - { role: PowerDNS.dnsdist, when: dnsdist == true, tags: [dnsdist] }
    - { role: dnsdist-post, when: dnsdist == true, tags: [dnsdist]}
    - { role: dnscrypt-wrapper, when: dnscrypt_wrapper == true, tags: [dnscrypt_wrapper] }
    - { role: netdata, when: netdata == true, tags: [netdata] }
    - { role: publicarray.haproxy, tags: [haproxy] }
