---
# https://github.com/jedisct1/dnscrypt-server-docker/blob/master/unbound.sh
- name: Install unbound
  package: name=unbound state=present

- name: Set cache_memory variable from shell command
  shell: "echo $(($(($((1024 * $((fgrep MemAvailable /proc/meminfo || fgrep MemTotal /proc/meminfo) | sed 's/[^0-9]//g' ))) - 12582912)) / 3))"
  register: cache_memory
  check_mode: no

- name: Set threads variable from shell command
  shell: "if [ $(nproc) -gt 1 ]; then echo $((nproc - 1)); else echo 1; fi"
  register: threads
  check_mode: no

- name: Setup or update of the root trust anchor for DNSSEC validation
  command: unbound-anchor

- name: Copy unbound configuration
  template: src=unbound.conf dest=/etc/unbound/unbound.conf
  notify: Restart unbound

- name: Check unbound configuration
  command: unbound-checkconf

- stat: path=/etc/unbound/unbound_control.pem
  register: p

- name: Setup unbound-control
  when: not p.stat.exists
  command: unbound-control-setup

- stat: path=/etc/unbound/named.cache
  register: p

- name: Get root-hints cache
  when: not p.stat.exists
  get_url:
    url: ftp://FTP.INTERNIC.NET/domain/named.cache
    dest: /etc/unbound/named.cache

- name: Ensure unbound is running
  service:
    name: unbound
    state: started
    enabled: true
    pattern: "unbound"
