---
# dependency to build dnscrypt-wrapper
- name: read platform variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"
  tags: [always]

- name: Install build/dependency packages
  package:
    name: "{{item}}"
    state: present
  with_items: "{{dnscrypt_packages}}"

- name: Install dnscrypt-wrapper - git clone
  when: ansible_os_family != 'FreeBSD'
  git:
    repo: 'https://github.com/cofyc/dnscrypt-wrapper.git'
    dest: '/usr/src/dnscrypt-wrapper'
    recursive: yes
    update: yes
    force: yes
  tags:
    - skip_ansible_lint

- name: Install dnscrypt-wrapper - make configure
  when: ansible_os_family != 'FreeBSD'
  make:
    chdir: '/usr/src/dnscrypt-wrapper'
    target: configure

- name: Install dnscrypt-wrapper - ./configure
  when: ansible_os_family != 'FreeBSD'
  command: '"{{ item }}" chdir=/usr/src/dnscrypt-wrapper'
  with_items:
    - ./configure

- name: Install dnscrypt-wrapper - make install
  when: ansible_os_family != 'FreeBSD'
  make:
    chdir: '/usr/src/dnscrypt-wrapper'
    target: install

- name: Install dnscrypt-wrapper
  pkgng: name=dnscrypt-wrapper state=present
  when: ansible_os_family == 'FreeBSD'
