# Start with the ubuntu image
FROM centos:7
# Install ansible dependencies
RUN yum install -y python-yaml python-jinja2 git
# Clone ansible repo (could also add the ansible PPA and do an apt-get install instead)
RUN git clone http://github.com/ansible/ansible.git /tmp/ansible

# Set variables for ansible
ENV PATH "/tmp/ansible/bin:${PATH}"
ENV ANSIBLE_LIBRARY /tmp/ansible/library
ENV PYTHONPATH /tmp/ansible/lib:$PYTHON_PATH

# Install requirements
ADD ./requirements.yml /etc/ansible/requirements.yml
WORKDIR /etc/ansible
RUN ansible-galaxy install -r requirements.yml

# Run ansible using the playbook
ADD ./ /etc/ansible/
RUN ansible-playbook playbook.yml -i "localhost," -c local --diff --tags "init"
RUN ansible-playbook playbook.yml -i "localhost," -c local --diff --tags "nsd"
RUN ansible-playbook playbook.yml -i "localhost," -c local --diff --tags "unbound"
# RUN ansible-playbook playbook.yml -i "localhost," -c local --diff --tags "pdns_recursor"
RUN ansible-playbook playbook.yml -i "localhost," -c local --diff --tags "dnsdist"
# RUN ansible-playbook playbook.yml -i "localhost," -c local --diff --tags "dnscrypt_wrapper"
RUN ansible-playbook playbook.yml -i "localhost," -c local --diff --tags "netdata"
# RUN ansible-playbook playbook.yml -i "localhost," -c local --diff --tags "haproxy"
# RUN ansible-playbook playbook.yml -i "localhost," -c local --diff
