---
# Heavily inspired by: https://github.com/reallyenglish/ansible-role-nsd
# thanks to Tomoyuki Sakurai and Contributors

- include_vars:
    file: "{{ ansible_os_family }}.yml"
  tags: [always, update-opennic-tlds]

- name: Install nsd
  package:
    name: nsd
    state: present
  when: ansible_os_family != 'FreeBSD'

- name: Config nsd - set ROOT_SERVER option in make.conf
  template:
    src: make.conf
    dest: "/etc/make.conf"
  when: ansible_os_family == 'FreeBSD'

- name: Install nsd from port
  portinstall:
    name: nsd
    state: present
  when: ansible_os_family == 'FreeBSD'

- name: Create db directory
  file:
    path: "{{ nsd_db_dir }}"
    mode: 0750
    owner: "{{ nsd_user }}"
    group: "{{ nsd_group }}"
    state: directory
  notify: Restart nsd

- name: Create zonefiles directory
  file:
    path: "{{ nsd_zonesdir }}"
    mode: 0750
    owner: "{{ nsd_user }}"
    group: "{{ nsd_group }}"
    state: directory
  notify: Restart nsd

- name: Create nsd.conf
  template:
    src: nsd.conf
    dest: "{{ nsd_conf }}"
    # validate: nsd-checkconf %s
  notify: Reload nsd

- name: Check nsd configuration
  command: "nsd-checkconf {{ nsd_conf }}"
  # check_mode: no

- name: Run nsd-control-setup
  command: nsd-control-setup
  args:
    creates: "{{ nsd_conf_dir }}/nsd_control.key"
  when: nsd_remote_control == "yes"

- name: Get OpenNIC tlds
  # dig @45.56.115.189 TXT tlds.opennic.glue +short | grep -v '^;' | sed s/\"//g | tr " " "\n"
  shell: "dig @45.56.115.189 TXT tlds.opennic.glue +short | grep -v '^;' | sed s/\\\"//g | tr \" \" \"\\n\""
  register: opennic_tlds_temp
  check_mode: false
  when: opennic is defined and opennic
  tags: [update-opennic-tlds, unbound]

- debug:
    msg: "{{opennic_tlds_temp.stdout_lines}}"
  when: opennic is defined and opennic
  tags: [update-opennic-tlds]

- name: Set OpenNIC tlds
  set_fact:
    opennic_tlds: "{{opennic_tlds_temp.stdout_lines}}"
  when: opennic is defined and opennic
  tags: [update-opennic-tlds]

- name: Create nsd/conf.d directory
  file:
    path: "{{nsd_conf_dir}}/conf.d"
    state: directory

- name: Copy OpenNIC config
  template:
    src: opennic.conf
    dest: "{{nsd_conf_dir}}/conf.d/opennic.conf"
  notify: Restart nsd
  when: opennic is defined and opennic
  tags: [update-opennic-tlds]

# - name: Check nsd configuration
#   command: "nsd-checkconf {{nsd_conf_dir}}/conf.d/opennic.conf"
#   # check_mode: no

# SELinux
- name: Configure ports for SELinux (install policycoreutils-python)
  package:
    name: policycoreutils-python # for semanage
    state: present
  when: ansible_selinux.status != "Missing selinux Python library"

- name: Configure ports for SELinux (mark udp port for dns)
  seport:
    ports: "{{nsd_port}}"
    proto: udp
    setype: dns_port_t
    state: present
  when: ansible_selinux.status != "Missing selinux Python library"

- name: Configure ports for SELinux (mark tcp port for dns)
  seport:
    ports: "{{nsd_port}}"
    proto: tcp
    setype: dns_port_t
    state: present
  when: ansible_selinux.status != "Missing selinux Python library"

- name: Ensure nsd is running
  service:
    name: nsd
    state: started
    enabled: true
    pattern: "nsd"
  tags: [nsd]
