---
- name: Create /var/dns-recursor folder
  file:
    path: /var/dns-recursor
    state: directory

# https://www.internic.net/domain/named.cache
# Update root.hints every six months or so
- name: Get root-hints cache
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: /var/dns-recursor/root.hints
