---

# TODO: sysvinit and upstart
- debug: "var=ansible_service_mgr"
- name: Copy custom.conf for dnsdist service - systemd (Drops dnsdist privilege)
  template:
    src: custom.conf
    dest: /etc/systemd/system/dnsdist.service.d/custom.conf
  notify: Restart dnsdist
  tags: [dnsdist_post, dnsdist]

- name: Ensure dnsdist is running
  service:
    name: dnsdist
    state: started
    enabled: yes
    pattern: "dnsdist"
  tags: [dnsdist_post, dnsdist]
