---

# TODO: sysvinit and upstart
- debug: "var=ansible_service_mgr"

- name: Create folder for custom dnsdist service - systemd (Drops dnsdist privilege)
  file:
    path: /etc/systemd/system/dnsdist.service.d/
    state: directory
  tags: [dnsdist_post, dnsdist]

- name: Copy custom.conf for dnsdist service - systemd (Drops dnsdist privilege)
  template:
    src: custom.conf
    dest: /etc/systemd/system/dnsdist.service.d/custom.conf
  notify: Restart dnsdist
  tags: [dnsdist_post, dnsdist]

- name: Copy functions.lua for dnsdist
  template:
    src: 01functions.lua
    dest: /etc/dnsdist/config.d/01functions.conf
  notify: Restart dnsdist
  tags: [dnsdist_post, dnsdist]

- name: Copy dnscrypt.lua for dnsdist
  template:
    src: 02dnscrypt.lua
    dest: /etc/dnsdist/config.d/02dnscrypt.conf
  notify: Restart dnsdist
  tags: [dnsdist_post, dnsdist]

- name: Ensure dnsdist is running
  service:
    name: dnsdist
    state: started
    enabled: yes
    pattern: "dnsdist"
  tags: [dnsdist_post, dnsdist]
