---

- name: Read platform varables
  include_vars:
    file: "{{ ansible_os_family }}.yml"
  tags: [always, update-opennic-tlds]
  when: ansible_os_family == 'FreeBSD' or ansible_os_family == 'OpenBSD'

- name: Install dnsdist dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
    # build dependecies
    # - libatomic_ops
    - gmake
    - bison
    - pkgconf
    # lib dependecies
    - boost-libs
    - protobuf
    - re2
    - libsodium
    - libedit
    - lua52
  tags: [dnsdist_post, dnsdist]
  when: ansible_os_family == 'FreeBSD'

# note: freebsd needs 1.5GB of free memory to compile dnsdist!
- name: Install dnsdist from port - FreeBSD
  portinstall:
    name: dns/dnsdist
    state: present
    use_packages: true
  tags: [dnsdist_post, dnsdist]
  when: ansible_os_family == 'FreeBSD'

- name: Install dnsdist from port - OpenBSD
  package:
    name: dnsdist
    state: present
  tags: [dnsdist_post, dnsdist]
  when: ansible_os_family == 'OpenBSD'

- name: Copy dnsdist config
  template:
    src: dnsdist.conf
    dest: "{{_dnsdist.config}}"
  when: ansible_os_family == 'FreeBSD' or ansible_os_family == 'OpenBSD'
  notify: Restart dnsdist
  tags: [dnsdist_post, dnsdist]

# TODO: sysvinit and upstart
# - debug: "var=ansible_service_mgr"

- name: Create folder for custom dnsdist service - systemd (Drops dnsdist privilege)
  file:
    path: /etc/systemd/system/dnsdist.service.d/
    state: directory
  when: ansible_os_family != 'FreeBSD'
  tags: [dnsdist_post, dnsdist]

- name: Copy custom.confs service - systemd (Drops dnsdist privilege)
  template:
    src: custom.conf
    dest: /etc/systemd/system/dnsdist.service.d/custom.conf
  notify: Restart dnsdist
  when: ansible_os_family != 'FreeBSD'
  tags: [dnsdist_post, dnsdist]

# - name: Temp file permission fix (allows dnsdist to read the config file)
#   file:
#     path: /etc/dnsdist/dnsdist.conf
#     owner: dnsdist
#     group: dnsdist
#     mode: 0644
#   when: ansible_os_family != 'FreeBSD'

# - debug: "var=ansible_default_ipv4"

- name: Copy dnscrypt.lua
  template:
    src: dnscrypt.lua
    dest: /etc/dnsdist/config.d/01dnscrypt.conf
  notify: Restart dnsdist
  tags: [dnsdist_post, dnsdist]

- name: Check config (hopefully creates the certs and keys?)
  command: dnsdist --check-config
  tags: [dnsdist_post, dnsdist]
  changed_when: false
  check_mode: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure dnsdist is running
  service:
    name: dnsdist
    state: started
    enabled: yes
    pattern: "dnsdist"
  tags: [dnsdist_post, dnsdist]
