---

send_email: "no"
sendmail_path: ''
curl_path: ''
default_recipient_email: "root"

send_pushover: "yes"
pushover_app_token: ""
default_recipient_pushover: ""

send_pushbullet: "yes"
pushbullet_access_token: ""
default_recipient_pushbullet: ""

send_twilio: "yes"
twilio_account_sid: ""
twilio_account_token: ""
twilio_number: ""
default_recipient_twilio: ""

send_messagebird: "yes"
messagebird_access_key: ""
messagebird_number: ""
default_recipient_messagebird: ""

send_telegram: "yes"
telegram_bot_token: ""
default_recipient_telegram: ""

send_slack: "yes"
slack_webhook_url: ""
default_recipient_slack: ""

send_discord: "yes"
discord_webhook_url: ""
default_recipient_discord: ""

send_hipchat: "yes"
hipchat_server: "api.hipchat.com"
hipchat_auth_token: ""
default_recipient_hipchat: ""

send_kafka: "yes"
kafka_url: ""
kafka_sender_ip: ""

send_pd: "yes"
default_recipient_pd: ""
