---

- include_vars:
    file: "{{ ansible_os_family }}.yml"
  tags: [always]

# Install packages
- name: Install packages
  package:
    name: "{{item}}"
    state: present
  with_items: "{{_packages}}"

# ansible_os_family == [RedHat, Debian, Suse, Gentoo, Archlinux, Solaris, Alpine, FreeBSD, OpenBSD]

#fix for:
# TASK [jeffwidman.yum-cron : Ensures cron(ie) service is running] ***************
# fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service crond: host"}
# to retry, use: --limit @/etc/ansible/test.retry
- name: fix crond service
  package:
    name: cronie
    state: present
  when: ansible_distribution == 'CentOS' and ansible_lsb.major_release|int >= 7

- name: enable cronie
  service:
    name: crond
    enabled: yes
    use: service
  when: ansible_distribution == 'CentOS' and ansible_lsb.major_release|int >= 7

#
# - group:
#     name: pdns
#     state: present
#     when: ansible_os_family == 'Debian'

# - user:
#     name: pdns
#     state: present
#     comment: "pdns-recursor"
#     group: pdns
#     when: ansible_os_family == 'Debian'

# - group:
#     name: pdns-recursor
#     state: present
#     when: ansible_os_family == 'RedHat'

# - user:
#     name: pdns-recursor
#     state: present
#     comment: "pdns-recursor"
#     group: pdns-recursor
#     when: ansible_os_family == 'RedHat'
