---
# curl
- name: Install packages for Debian OS family
  apt: pkg={{ item }} state=present
  when: ansible_os_family == 'Debian'
  with_items: "{{ubuntu_installed_packages}}"

- name: Install packages for RedHat OS family
  yum: name={{ item }} state=present
  when: ansible_os_family == 'RedHat'
  with_items: "{{redhat_installed_packages}}"

#
# - group:
#     name: pdns
#     state: present
#     when: ansible_os_family == 'Debian'

# - user:
#     name: pdns
#     state: present
#     comment: "pdns-recursor"
#     group: pdns
#     when: ansible_os_family == 'Debian'

# - group:
#     name: pdns-recursor
#     state: present
#     when: ansible_os_family == 'RedHat'

# - user:
#     name: pdns-recursor
#     state: present
#     comment: "pdns-recursor"
#     group: pdns-recursor
#     when: ansible_os_family == 'RedHat'
